### ISSUE TITLE
Failed test raises unhandled exception

### ISSUE THREAD

**Issue by buricl** [buricl/FRUITPy#2]
```
STOP 1
Traceback (most recent call last):
  File "../../repos/FRUITPy/FRUIT.py", line 450, in <module>
    ts.build_run(args.driver, args.build)
  File "../../repos/FRUITPy/FRUIT.py", line 427, in build_run
    return self.run(run_command, num_procs, output_dir, mpi)
  File "../../repos/FRUITPy/FRUIT.py", line 331, in run
    output = check_output(run)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['./unit_test']' returned non-zero exit status 1
```

subprocess.check_output raises an unhandled exception when process returns non-zero exit code. This is triggered by at least one failing test.

**Comment by buricl** [comment]
Fixed in https://github.com/buricl/FRUITPy/commit/64b353d2b8c3bf5aee6c292f6ed41620380a6655. Also, some unused imports were deleted.

**Comment by buricl** [comment]
Merged to master

**Comment by buricl** [comment]
Merged to master
